### ISSUE TITLE
bower install command errors

### ISSUE THREAD

**Issue by jbrychka26** [vaadin/expense-manager-ng2-demo#10]
Getting the following errors when running the bower install command:
bower ENORESTARGET  Tag/branch feature/angular-rc-0 does not exist

Additional error details:
Available tags: 3.0.0, 3.0.0-alpha1, 3.0.0-alpha2, 3.0.0-alpha3, 3.0.0-alpha4, 3
.0.0-alpha5, 3.0.0-alpha6, 3.0.0-alpha7, 3.0.0-alpha8, 3.0.0-alpha9, 3.0.0-beta1
, 3.0.0-rc1, 3.0.0-rc2, 3.1.0-beta1, 3.1.0-beta2, 3.1.0-rc1
Available branches: 3.1, feature/CHARTS-202, feature/react-component-data-bindin
g, master, private-chart, task/CHARTS-170, task/CHARTS-232, task/CHARTS-383, tas
k/CHARTS-505, task/dataseries_parsestring, task/merge_ng2

**Comment by samiheikki** [comment]
Thanks for the bug report!

Fixed in https://github.com/vaadin/expense-manager-ng2-demo/commit/f4ad85021dc43a0e3ede73756f56085cab6916c4
