### ISSUE TITLE
Bower install fails

### ISSUE THREAD

**Issue by johannesh2** [vaadin/expense-manager-ng2-demo#14]
Trying to run npm install and bower install, but bower install fails many times.

The error is: bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/PolymerElements/paper-toast.git", exit code of #128 fatal: unable to connect to github.com

Is this my crappy conference connection or something else? Feel free to close if nothing serious. I can't compile the demo.

**Comment by samiheikki** [comment]
I can't reproduce this. Noticed that paper-toast is installed with paper-elements and as it's own, but can't believe that it would break it.

@johannesh2 can you remove paper-toast from bower.json file and try bower install again. Let's see if that does the trick.

**Comment by johannesh2** [comment]
That didn't help and now that I'm back again on a more reliable connection the bower install succeeds. Closing this.

**Comment by amahdy** [comment]
It works only in Finland
