### ISSUE TITLE
Code clutter

### ISSUE THREAD

**Issue by geneeblack** [vaadin/expense-manager-ng2-demo#18]
Is there a code base for the ng2 demo that doesn't use all the Reflect clutter and implements standard ng2 constructs i.e.

    import { Core } from '@angular/core';

vs 

    var core_1 = require('@angular/core');

I would like to view this project as an implementation using ng2, rather than have to wade through all of the meta data which I assume is being consumed by an editor rather than simply a test runner?

**Comment by platosha** [comment]
In this project, the original TypeScript source files are also committed here, in this repository, alongside with the compiled JavaScript files. Please look into the .ts files, for example, `app/app.module.ts`, not `app/app.module.js`.

It might be also useful to loot at the https://github.com/vaadin/angular2-polymer-quickstart project. The application there is much smaller, and also has only the .ts source files committed.
